[tool.poetry]
name = "llm-code-context"
version = "0.0.1"
description = "Help with copy/paste code into chat"
authors = ["restlessronin <88921269+restlessronin@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "llm_code_context", from = "src"}]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
jinja2 = "^3.1.3"
pyperclip = "^1.8.2"
wxpython = "^4.2.1"
pathspec = "^0.12.1"

[tool.poetry.group.dev.dependencies]
black = "^24.4.0"
isort = "^5.13.2"
pytest = "^7.3.1"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.black]
line-length = 100
target-version = ['py312']

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
