__info__: 'This project uses llm-context. For more information, visit: https://github.com/cyberchitta/llm-context.py
  or https://pypi.org/project/llm-context/'
profiles:
  lc-code:
    base: lc-gitignores
    description: Default profile for software projects, using lc-gitignores base profile.
    prompt: lc-prompt.md
  lc-gitignores:
    description: Base ignore patterns for code files, customize this for project-specific
      ignores.
    gitignores:
      diagram_files:
      - .git
      - '*.jpg'
      - '*.jpeg'
      - '*.png'
      - '*.gif'
      - '*.bmp'
      - '*.svg'
      - '*.mp4'
      - '*.mkv'
      - '*.avi'
      - '*.mov'
      - '*.wmv'
      - '*.mp3'
      - '*.wav'
      - '*.flac'
      - '*.ttf'
      - '*.otf'
      - '*.woff'
      - '*.woff2'
      - '*.eot'
      - '*.ico'
      - '*.pdf'
      - '*.zip'
      - '*.rar'
      - '*.7z'
      - '*.tar'
      - '*.exe'
      - '*.dll'
      - '*.so'
      - '*.dylib'
      - '*.map'
      full_files:
      - 'tests/'
      - '*.md'
      - '*.scm'
      - '*.yaml'
      - .git
      - .gitignore
      - .llm-context/
      - '*.tmp'
      - '*.lock'
      - package-lock.json
      - yarn.lock
      - pnpm-lock.yaml
      - go.sum
      - elm-stuff
      - LICENSE
      - CHANGELOG.md
      - README.md
      - .env
      - .dockerignore
      - Dockerfile
      - docker-compose.yml
      - '*.log'
      - '*.svg'
      - '*.png'
      - '*.jpg'
      - '*.jpeg'
      - '*.gif'
      - '*.ico'
      - '*.woff'
      - '*.woff2'
      - '*.eot'
      - '*.ttf'
      - '*.map'
      outline_files:
      - 'tests/'
      - '*.md'
      - '*.scm'
      - '*.yaml'
      - .git
      - .gitignore
      - .llm-context/
      - '*.tmp'
      - '*.lock'
      - package-lock.json
      - yarn.lock
      - pnpm-lock.yaml
      - go.sum
      - elm-stuff
      - LICENSE
      - CHANGELOG.md
      - README.md
      - .env
      - .dockerignore
      - Dockerfile
      - docker-compose.yml
      - '*.log'
      - '*.svg'
      - '*.png'
      - '*.jpg'
      - '*.jpeg'
      - '*.gif'
      - '*.ico'
      - '*.woff'
      - '*.woff2'
      - '*.eot'
      - '*.ttf'
      - '*.map'
    only-include:
      diagram_files:
      - '**/*'
      full_files:
      - '**/*'
      outline_files:
      - '**/*'
templates:
  context: lc-context.j2
  context-mcp: lc-context-mcp.j2
  definitions: lc-definitions.j2
  files: lc-files.j2
  highlights: lc-highlights.j2
  prompt: lc-prompt.j2
